print('CRIANDO UMA ESTRUTURA COMPOSTA - TUPLA')
lanche = ('Hamburger', 'Suco', 'Pizza', 'Pudim')
print(lanche)
print(lanche[0])
print(lanche[1])
print(lanche[2])
print(lanche[3])
print(lanche [-1])
print(lanche [-2])
print(lanche [-3])
print(lanche [-4])
print(lanche[1:3])
print(lanche[2:])
print(lanche[:2])
print(lanche[-2:])
print(lanche[-3:])
print(len(lanche))


