y = int(input('Digite um número para ver sua tabuada: '))
print('-' *12)
print('{} x {:2} = {}'.format(y, 1, (y*1)))
print('{} x {:2} = {}'.format(y, 2, (y*2)))
print('{} x {:2} = {}'.format(y, 3, (y*3)))
print('{} x {:2} = {}'.format(y, 4,(y*4)))
print('{} x {:2} = {}'.format(y, 5, (y*5)))
print('{} x {:2} = {}'.format(y, 6, (y*6)))
print('{} x {:2} = {}'.format(y, 7, (y*7)))
print('{} x {:2} = {}'.format(y, 8, (y*8)))
print('{} x {:2} = {}'.format(y, 9, (y*9)))
print('{} x {:2} = {}'.format(y, 10, (y*10)))
print('-'*12)

