print('=' *34)
print('                    LISTAGEM DE PREÇOS')
print('=' *34)
lista = ('Lapis', 1.75, 'Borracha', 2.00, 'Caderno', 15.90, 'Estojo', 25.00, 'Transferidor', 4.20,
         'Compasso', 9.99, 'Mochila', 120.32, 'Canetas', 22.30, 'Livro', 34.90)
print('{}.................................................R$     {:.2f}'.format(lista[0], lista[1]))
print('{}...........................................R$     {:.2f}'.format(lista[2], lista[3]))
print('{}............................................R$   {:.2f}'.format(lista[4], lista[5]))
print('{}................................................R$   {:.2f}'.format(lista[6], lista[7]))
print('{}......................................R$     {:.2f}'.format(lista[8], lista[9]))
print('{}.........................................R$     {:.2f}'.format(lista[10], lista[11]))
print('{}..............................................R$ {:.2f}'.format(lista[12], lista[13]))
print('{}.............................................R$   {:.2f}'.format(lista[14], lista[15]))
print('{}...................................................R$   {:.2f}'.format(lista[16], lista[17]))
print('=' *34)
