print('MATRIZ')
matriz = list()
n00 = int(input('Digite um número para a posição 0 , 0: '))
matriz.append(n00)
n01 = int(input('Digite um número para a posição 0 , 1: '))
matriz.append(n01)
n02 = int(input('Digite um número para a posição 0 , 2: '))
matriz.append(n02)
n10 = int(input('Digite um número para a posição 1 , 0: '))
matriz.append(n10)
n11 = int(input('Digite um número para a posição 1 , 1: '))
matriz.append(n11)
n12 = int(input('Digite um número para a posição 1 , 2: '))
matriz.append(n12)
n20 = int(input('Digite um número para a posição 2 , 0: '))
matriz.append(n20)
n21 = int(input('Digite um número para a posição 2 , 1: '))
matriz.append(n21)
n22 = int(input('Digite um número para a posição 2 , 2: '))
matriz.append(n22)
print(f' [  {matriz[0]}  ]  [  {matriz[1]}  ]  [  {matriz[2]}  ]')
print(f' [  {matriz[3]}  ]  [  {matriz[4]}  ]  [  {matriz[5]}  ]')
print(f' [  {matriz[6]}  ]  [  {matriz[7]}  ]  [  {matriz[8]}  ]')
